apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:070651558558:certificate/40eb319b-20f5-4fd5-ae24-ce56e81fff13
  name: rancher-stable
