apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
- includeCRDs: true
  name: addons
  namespace: argocd
  repo: https://github.com/aws-samples/eks-blueprints-add-ons.git
  chartPath: chart
  valuesInline:
    cert-manager:
      enable: true
