{{- if and (.Values.rancher) (.Values.rancher.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: cattle-system
spec:
  source:
    repoURL: {{ .Values.repoUrl }}
    path: kustomize/rancher
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        rancher:
        {{- toYaml .Values.rancher | nindent 10 }}
      parameters:
      - name: "hostname"
        value: "devunifiedplatform.com"
      - name: "tls"
        value: "external"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.rancher.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  destination:
    server: 'https://kubernetes.default.svc'
  project: {{ .Values.argoProject | default "default" }}
{{- end -}}
