{{- if and (.Values.rancher) (.Values.rancher.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: kustomize/rancher
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        {{- toYaml .Values.rancher | nindent 10 }}
      parameters:
        - name: "hostname"
          value: "rancher.devunifiedplatform.com"
        - name: "tls"
          value: "external"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.rancher.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
