apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
- name: argo-cd
  namespace: argocd
  repo: https://argoproj.github.io/argo-helm

patches:
- path: patches/configmap.yaml
