apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
- includeCRDs: true
  name: argocd
  namespace: argocd
  repo: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd

patches:
- path: patches/configmap.yaml
