apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/KonSprin/argo_apps.git
    path: argo_apps/up_applications
    targetRevision: jarilio
  project: default
  syncPolicy:
    automated:
      retry:
        limit: 2
        backoff: 10
      prune: true
      selfHeal: true
