apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:665849776193:certificate/85b88d78-ae34-476f-884f-7c4fb38608cd
  name: rancher-stable
