apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cattle-system

helmCharts:
- includeCRDs: true
  name: rancher
  namespace: cattle-system
  releaseName: rancher-stable
  repo: https://releases.rancher.com/server-charts/stable
  version: 2.7.3
  valuesInline:
    hostname: devunifiedplatform.com
    tls: external

patches:
- path: patches/ingress.yaml
